title: Five Hundred Miles
author: jieshi cheng
description: It's a blog of my thinking. Include CS technique and life experience

highlighter: null
permalink: /:title

url:
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
